name: bwu_docker
author: Guenter Zoechbauer <guenter@gzoechbauer.com>
homepage: http://github.com/bwu-dart/bwu_docker
version: 0.1.0
environment:
  sdk: '>=1.10.0 <2.0.0'

description: Dart client for the Docker remote API

dependencies:
  crypto: '^0.9.0'
  intl: '^0.12.2'
  http: '^0.11.2'
  quiver: '^0.21.3'

dev_dependencies:
#  bwu_utils_dev:
#    path: ../bwu_utils_dev
  test: '>=0.12.0 < 0.13.0'
#    git: git@github.com:dart-lang/test.git
  grinder: any

dependency_overrides:
  args: '>=0.13.0 <0.14.0'
#  analyzer: '>=0.25.0 <0.26.0' # for grinder analyze task
  matcher: '>=0.12.0 < 0.13.0'

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart
