name: bwu_docker
author: Guenter Zoechbauer <guenter@gzoechbauer.com>
homepage: http://github.com/bwu-dart/bwu_docker
description: Typed Dart client for the Docker JSON remote API.
  Makes it easy to automate Docker tasks or build a Docker-dashboard.
version: 0.3.0
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  collection: '^1.1.0'
  crypto: '^0.9.0'
  http: '^0.11.2'
  quiver_hashcode: '^1.0.0-dev.1'
  stack_trace: '^1.2.1'

dev_dependencies:
  bwu_grinder_tasks: '^0.1.0'
  grinder: '>=0.7.0 <0.9.0'
  test: '^0.12.3+1'

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart
